{% set name = "sortednp" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da5a42868cf833542b46582cff54f500df6388d639db42bb6776edd535d9fb35

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy =1.14
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }} 
    - python

test:
  imports:
    - sortednp
    - sortednp.tests

about:
  home: https://gitlab.sauerburger.com/frank/sortednp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Merge and intersect sorted numpy arrays.
  dev_url: https://gitlab.sauerburger.com/frank/sortednp

extra:
  recipe-maintainers:
    - tschoonj
