{% set name = "sortednp" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6dbd9964ac49eb1822846f880823b44c5311f7c10b2087532db33dc3e32e74d1

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - numpy >=1.14
    - pip
    - python
  run:
    - python

test:
  imports:
    - sortednp
    - sortednp.tests

about:
  home: https://gitlab.sauerburger.com/frank/sortednp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Merge and intersect sorted numpy arrays.
  dev_url: https://gitlab.sauerburger.com/frank/sortednp

extra:
  recipe-maintainers:
    - tschoonj
