{% set name = "sortednp" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sortednp-{{ version }}.tar.gz
  sha256: 6dbd9964ac49eb1822846f880823b44c5311f7c10b2087532db33dc3e32e74d1

build:
  skip: true  # [py<37 or py>=313]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy >=1.17.3,<2
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sortednp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.sauerburger.com/frank/sortednp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Merge and intersect sorted numpy arrays.
  dev_url: https://gitlab.sauerburger.com/frank/sortednp

extra:
  recipe-maintainers:
    - tschoonj
