{% set name = "sortednp" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c662155ece0969ca058482a35b297ad435c3108b5eb111b3caa1388fc638ffc

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy >=1.14
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - sortednp
    - sortednp.tests

about:
  home: https://gitlab.sauerburger.com/frank/sortednp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Merge and intersect sorted numpy arrays.
  dev_url: https://gitlab.sauerburger.com/frank/sortednp

extra:
  recipe-maintainers:
    - tschoonj
