# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RyGthFTp3u0WsuHbbe0SEU4W6nx3gQzsyYkDU+8NVZhbELIx39h2RxoCcx3dgAtpetExauPGSyavvLHmhzNOz/nrCMyeanl96beCaGfObHZOanq3qN7XIfYNsgG/lM/16Hu9NubSFe57H94V6DbRjT7UpHI+fnP3kH4bo+JheVTRkoi7aWE9AfMBjxfMXy3TE0JUi8OfqH2lJgpFl4m38KMs/DEeqzXWcIUlVVdG51kdsgfeYJGb/fHKH4KiKk+CljBOwkDXKrDhmK7en0ytx+NFsATIRmK85MIFTsUAi21NPgXz4Fo0hj76HoR7B2SFUAh0NuQ/2VoZE72ACwxJYPvNizL0bc2Wx41Eh/EJL/qj38w1NJ5R7139uvbvhFabxJ9lTyj7Axk/B6HA72+y3EGAEV1ZQL80CwC1+YjRE4lIgZOJHkhHUTZoNB2MPBY5C5JuC2prWmi2na001dWaXXp3lEC9nr01d8WCV7/HUo4xG/IfGLWbKM+7F2Vdj5MICjGBIACFgt5WyQQa/h1RM8hlh/7CQH77vGPnxKQFBSqxFhRoMOQOGC/7wvmanupp5Ikw8nr/3uBwctaMcNM/HaSiQg/lkWlEg7RJZndXPkb+PQKV0qswkG3ZJouI/nLQIdWmvBCSsWlTsgBb94joahmT4Vvcu4grRmZaNujberM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml