travis:
  secure:
    BINSTAR_TOKEN: RyGthFTp3u0WsuHbbe0SEU4W6nx3gQzsyYkDU+8NVZhbELIx39h2RxoCcx3dgAtpetExauPGSyavvLHmhzNOz/nrCMyeanl96beCaGfObHZOanq3qN7XIfYNsgG/lM/16Hu9NubSFe57H94V6DbRjT7UpHI+fnP3kH4bo+JheVTRkoi7aWE9AfMBjxfMXy3TE0JUi8OfqH2lJgpFl4m38KMs/DEeqzXWcIUlVVdG51kdsgfeYJGb/fHKH4KiKk+CljBOwkDXKrDhmK7en0ytx+NFsATIRmK85MIFTsUAi21NPgXz4Fo0hj76HoR7B2SFUAh0NuQ/2VoZE72ACwxJYPvNizL0bc2Wx41Eh/EJL/qj38w1NJ5R7139uvbvhFabxJ9lTyj7Axk/B6HA72+y3EGAEV1ZQL80CwC1+YjRE4lIgZOJHkhHUTZoNB2MPBY5C5JuC2prWmi2na001dWaXXp3lEC9nr01d8WCV7/HUo4xG/IfGLWbKM+7F2Vdj5MICjGBIACFgt5WyQQa/h1RM8hlh/7CQH77vGPnxKQFBSqxFhRoMOQOGC/7wvmanupp5Ikw8nr/3uBwctaMcNM/HaSiQg/lkWlEg7RJZndXPkb+PQKV0qswkG3ZJouI/nLQIdWmvBCSsWlTsgBb94joahmT4Vvcu4grRmZaNujberM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
